app = "financial-advisor-frontend"

[build]
  image = ""

[env]
  NEXT_PUBLIC_API_URL = "https://financial-advisor-backend.fly.dev"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "1s"
    port = 3000
